import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPOSITORY_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ASSET_DIRECTORY = path.join(REPOSITORY_ROOT, "packages", "studio", "assets", "presets");
const GENERATED_MODULE = path.join(
  REPOSITORY_ROOT,
  "packages",
  "assets",
  "src",
  "generated-images.ts",
);
const FIXTURE_DIRECTORY = path.join(REPOSITORY_ROOT, "fixtures", "scripts");

/**
 * Fixture image slots this script owns. Every fixture that shows a picture
 * draws from the same four assets, so none of them can drift back to a
 * hand-authored placeholder while the rest are refreshed. `fit` stays with
 * the slot: image-attach exists to show cover against contain.
 */
const FIXTURE_SLOTS = [
  { file: "image-generation.json", role: "image", asset: "watercolorTraveler", fit: "cover" },
  { file: "image-attach.json", role: "user", asset: "vectorConf", fit: "cover" },
  { file: "image-attach.json", role: "assistant", asset: "boundsvgPipeline", fit: "contain" },
  { file: "image-attach-tui.json", role: "user", asset: "generic", fit: "cover" },
] as const;
const IMAGE_WIDTH = 768;
const IMAGE_HEIGHT = 512;
const BASE64_CHUNK_LENGTH = 100;

const ASSETS = [
  {
    key: "generic",
    constant: "GENERIC_GENERATED_IMAGE",
    fileName: "generic-generated-result.webp",
    alt: "抑えた配色の抽象的な紙の立体",
  },
  {
    key: "watercolorTraveler",
    constant: "WATERCOLOR_TRAVELER_IMAGE",
    fileName: "watercolor-traveler-dusk.webp",
    alt: "夕暮れの海辺を歩く旅人の水彩画",
  },
  {
    key: "vectorConf",
    constant: "VECTORCONF_IMAGE",
    fileName: "vectorconf-dawn-curves.webp",
    alt: "夜明けを思わせる静かなベジェ曲線のキービジュアル",
  },
  {
    key: "boundsvgPipeline",
    constant: "BOUNDSVG_PIPELINE_IMAGE",
    fileName: "boundsvg-render-pipeline.webp",
    alt: "ベクター構造がラスタ画像へ変わる描画パイプラインの抽象画",
  },
] as const;

type EmbeddedImage = {
  dataUrl: string;
  mediaType: "image/webp";
  width: number;
  height: number;
  alt: string;
  fit: "cover" | "contain";
};

function chunkBase64(base64: string): string[] {
  const chunks: string[] = [];
  for (let offset = 0; offset < base64.length; offset += BASE64_CHUNK_LENGTH) {
    chunks.push(base64.slice(offset, offset + BASE64_CHUNK_LENGTH));
  }
  return chunks;
}

function imageExpression(image: EmbeddedImage): string {
  const chunks = chunkBase64(image.dataUrl);
  return [
    "Object.freeze({",
    "  dataUrl: [",
    ...chunks.map((chunk) => `    ${JSON.stringify(chunk)},`),
    '  ].join(""),',
    `  mediaType: ${JSON.stringify(image.mediaType)},`,
    `  width: ${image.width},`,
    `  height: ${image.height},`,
    `  alt: ${JSON.stringify(image.alt)},`,
    `  fit: ${JSON.stringify(image.fit)},`,
    "})",
  ].join("\n");
}

const embeddedImages = new Map<string, EmbeddedImage>();
const moduleParts = [
  "/**",
  " * Generated by `pnpm assets:sync` from repository-owned WebP files.",
  " * Do not edit the base64 payloads by hand.",
  " */",
  "",
  "type GeneratedSampleImage = Readonly<{",
  "  dataUrl: string;",
  '  mediaType: "image/webp";',
  "  width: number;",
  "  height: number;",
  "  alt: string;",
  '  fit: "cover";',
  "}>;",
  "",
];

for (const asset of ASSETS) {
  const bytes = await readFile(path.join(ASSET_DIRECTORY, asset.fileName));
  const image: EmbeddedImage = {
    dataUrl: `data:image/webp;base64,${bytes.toString("base64")}`,
    mediaType: "image/webp",
    width: IMAGE_WIDTH,
    height: IMAGE_HEIGHT,
    alt: asset.alt,
    fit: "cover",
  };
  embeddedImages.set(asset.key, image);
  moduleParts.push(
    `const ${asset.constant}: GeneratedSampleImage = ${imageExpression(image)};`,
    "",
  );
}

moduleParts.push(
  "export const GENERATED_SAMPLE_IMAGES = Object.freeze({",
  ...ASSETS.map((asset) => `  ${asset.key}: ${asset.constant},`),
  "});",
  "",
);
await writeFile(GENERATED_MODULE, moduleParts.join("\n"), "utf8");

type FixtureScript = { messages?: Array<{ role?: unknown; images?: EmbeddedImage[] }> };

const fixtureFiles = [...new Set(FIXTURE_SLOTS.map((slot) => slot.file))];
for (const file of fixtureFiles) {
  const fixturePath = path.join(FIXTURE_DIRECTORY, file);
  const fixture = JSON.parse(await readFile(fixturePath, "utf8")) as FixtureScript;
  for (const slot of FIXTURE_SLOTS.filter((entry) => entry.file === file)) {
    // The slot is the first message of its role that already carries an
    // image, so a fixture can hold several pictures without them swapping.
    const target = fixture.messages?.find(
      (message) => message.role === slot.role && (message.images?.length ?? 0) > 0,
    );
    const asset = embeddedImages.get(slot.asset);
    if (!target || !asset) {
      throw new Error(`${file} has no ${slot.role} message holding an image`);
    }
    target.images = [{ ...asset, fit: slot.fit }];
  }
  await writeFile(fixturePath, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");
}
