export { planCameraTrack } from "./camera.js";
export {
  COMPOSER_LINE_RISE_MS,
  COMPOSER_MAX_EXTRA_LINES,
  COMPOSER_PANEL_SHRINK_MS,
  composerBasePanelAnimation,
  composerDraftAnimation,
  composerDraftLine,
  composerIdleAnimation,
  composerPanelAnimation,
  planComposerDraft,
  planComposerShove,
  planDraftTyping,
  sendButtonAnimation,
  sendMomentMs,
  userLandingMs,
  userTypingWindows,
  voiceCaptureWindows,
  voiceChromeAnimation,
  voiceConfirmedDraftAnimation,
  voiceConfirmMs,
} from "./composer.js";
export type {
  ComposerDraftPlan,
  DraftLayoutSequence,
  DraftLayoutSnapshot,
  DraftWrapOptions,
} from "./draft-layout.js";
export {
  DRAFT_FONT_FEATURES,
  draftClusterVisibleMs,
  planDraftLayoutSequence,
  planDraftText,
  visibleDraftPrefixLength,
} from "./draft-layout.js";
export type {
  DraftCompositionRange,
  DraftPhase,
  DraftTypedRange,
  DraftTypingIssue,
  DraftTypingProgram,
  ResolvedDraftTyping,
} from "./draft-typing.js";
export {
  analyzeDraftTyping,
  DRAFT_FINAL_REVEAL_MS,
  MIN_DRAFT_REVEAL_MS,
  normalizeDraftSource,
  resolveDraftTyping,
} from "./draft-typing.js";
export type { GeneratorIdentity, Metrics, RenderedBlock, SceneEnv, ScenePalette } from "./env.js";
export {
  accentInk,
  chromeInk,
  estimateTextWidthPx,
  fallbackFor,
  hexToRgb,
  hexToRgba,
  MONO_FALLBACK,
  MONO_FONT,
  messageSurfaceAlpha,
  metricsFor,
  paletteFor,
  SANS_FALLBACK,
  SANS_FONT,
  secondsLabel,
  sessionClockLabel,
  spacePx,
  spaceScaleFor,
  strokePx,
  TUI_CHAR_RATIO,
  TUI_FRAME_STROKE_PX,
  TUI_LINE_RATIO,
} from "./env.js";
export {
  collectChromeCharacters,
  collectProjectCharacters,
  describeMissingGlyphs,
  findMissingGlyphs,
  findProjectMissingGlyphs,
} from "./glyphs.js";
export { draftGraphemeCount, draftGraphemes } from "./graphemes.js";
export type { AppHighlightBeat } from "./highlight.js";
export { beatLiftPx, planAppHighlights, planBeatLift } from "./highlight.js";
export type { SceneAction } from "./interaction.js";
export { sceneActionMeta } from "./interaction.js";
export type { HighlightRun, InlineRun, InlineStyle, MarkdownBlock } from "./markdown.js";
export {
  highlightCode,
  markdownPlainText,
  markdownRevealCharacters,
  parseInlineMarkdown,
  parseMarkdown,
} from "./markdown.js";
export {
  contentAlignOffset,
  fitChromeScale,
  measureLineWidthPx,
  measureMessageHeights,
  measureWrappedLineCount,
  messageHeightCacheKey,
} from "./measure.js";
export {
  appAttachedImagesRegion,
  appChoiceOptionsRegion,
  appMessage,
  appMessageBand,
  appMessageInkWidthPx,
  pickerCloseMs,
  tuiMessage,
  tuiMessageInkWidthPx,
} from "./messages.js";
export type {
  AppearanceSettings,
  AssistantSurface,
  AttachedImage,
  BackdropId,
  CameraSettings,
  CameraStyle,
  ChromeSettings,
  ContentAlign,
  DisplaySettings,
  DraftSpanKind,
  FlowMode,
  FontChoice,
  FontSlot,
  FontsSettings,
  ImageSkeletonId,
  MessageAlign,
  MessageRole,
  MessageTimingOverride,
  ModelLabelIssueCode,
  PaginationSettings,
  ScriptBasis,
  ScriptFontProvenance,
  ScriptProvenance,
  SessionMessage,
  SurfaceMode,
  SvgentProject,
  ThemeId,
  TimingPreset,
  TimingSettings,
} from "./model.js";
export {
  AGENT_BEHAVIOR_PRESETS,
  BACKDROP_PRESETS,
  buildGoogleFontCssUrl,
  buildScriptPrompt,
  bundledFallbackFonts,
  CAMERA_MIN_SHOT_PRESET_MS,
  CAMERA_ZOOM_MAX,
  CAMERA_ZOOM_MIN,
  completionCount,
  createCompletionSpan,
  createImeSpan,
  createMessage,
  currentToolVersions,
  DEFAULT_PROJECT,
  DISPLAY_PRESETS,
  defaultProjectFor,
  deserializeProject,
  disclosureFor,
  draftTypedText,
  extractScriptJson,
  FALLBACK_FONT_ALIAS,
  FONT_ALIAS,
  GOOGLE_FONT_SUGGESTIONS,
  IMAGE_ROLES,
  imeConversionCount,
  MAX_DRAFT_RUN_CLUSTERS,
  MAX_IMAGE_BYTES,
  MAX_MESSAGE_CHARS,
  MAX_MESSAGE_IMAGES,
  MAX_MESSAGES,
  MESSAGE_TIMING_LIMITS,
  messageIdToken,
  modelLabelIssue,
  normalizeGoogleFontFamily,
  PASTE_TYPING_CPS,
  PROJECT_FILE_VERSION,
  parseDraftSegments,
  REENACTMENT_BADGE,
  resolveSafeModelLabel,
  SAFE_MODEL_LABEL,
  SCENE_PACING_PRESETS,
  SIMULATION_BADGE,
  SIZE_PRESETS,
  serializeProject,
  stripDraftMarkup,
  THEME_PRESETS,
  USER_INPUT_PRESETS,
} from "./model.js";
export type { BuiltScene, ProductMarkPlacement } from "./scene.js";
export { buildSvgentScene, productMarkPlacements } from "./scene.js";
export type {
  DraftTimelineIssue,
  HighlightWindow,
  MessageTiming,
  SessionTimeline,
} from "./timeline.js";
export {
  animatedRasterFps,
  buildTimeline,
  CHOICE_SEND_BEAT_MS,
  COMPLETION_ACCEPT_MS,
  choiceDraftTiming,
  choiceKeyingStartMs,
  composerDraftTimings,
  countVisibleCharacters,
  draftTimelineIssues,
  highlightWindow,
  IME_COMMIT_MS,
  IME_CONVERSION_MS,
  MAX_PROJECT_DURATION_MS,
  messageAtTime,
  paginateMessages,
} from "./timeline.js";
